### PR TITLE
Fix counter tracking

### PR DESCRIPTION
**Pull request by sauyon**
I'm just assuming that if the boss attacked before you, the attack is a counter. I can't really think of any other way to do it.

Counters are currently still being added to attack totals¸ which feels strange. Could consider adding a category of itself for counters but that seems like overkill.

Addresses #1

### CODE REVIEW

**Comment by sauyon** [comment]
Don't merge this yet, tracking has completely stopped working for me atm.

**Comment by sauyon** [comment]
I think it's an unrelated bug; possibly caused by the char name loading fix. Looking into that now.

**Comment by sauyon** [comment]
So at the moment it shows up in this form:

> sauyon(Counter) x

And it's expandable to show Attack 1.
I think multiple attack counters are possible, I'm trying to test that right now.
I'll probably add code to check whether the counter was a multiattack as well.

**Comment by sauyon** [comment]
The code for appending to the log could really use some sprucing up - for example, is there any particular reason why this:

```
if(!(turnDetails.details[i].type == "Chain Burst" ||
    (turnDetails.details[i].type == "Single" && turnDetails.details[i].details[0].details.length < 2) ||
    (turnDetails.details[i].type == "Counter" && turnDetails.details[i].details.length < 2) ||
    turnDetails.details[i].type == "CA"))
```

can't be written

```
if((turnDetails.details[i].details && turnDetails.details[i].details.length < 2) ||
   (turnDetails.details[i].details[0].details && turnDetails.details[i].details[0].details.length < 2))
```

or with some preprocessing just the latter parts of both ands?

**Comment by sauyon** [comment]
Though I suppose the biggest issue with it in my eyes is the .details.details.details.details stuff.

**Comment by Azryth** [comment]
multi counters are not an issue. If a character counters twice it's a separate attack. 


The problem with it is that there needs to be a special case for counters. The damage property of any counter in a turn is an array. All subsequent counters are a list... with an array in it... with the damage. Which is why the second counter in the image above doesn't have a type value.
capture

**Comment by Azryth** [comment]
Yeah, the code for the log is probably the ugliest thing among all the other ugly code I hacked together for this project. Here are my thoughts on that:
- The details details details is definitely ugly and needs to go.
- The reason I prefer the original over your suggestion is that in your suggestion it isn't immediately clear under what conditions the expression is true. 

I do plan on refactoring, but that'll probably be on the weekend. If you want to do something about it before then, go ahead. As long as it still works I'm not too particular about how it's written in the end.

**Comment by sauyon** [comment]
You're right, just tested it out. ATM it does this:
image
Fixing that now.

**Comment by sauyon** [comment]
Regarding the code log stuff, I'll refactor it myself I think; it's mostly a matter of me finding it ugly is all :stuck_out_tongue:.

(That said, I'll probably forget about it in the morning and/or decide cleaning up code is not worth doing)

**Comment by sauyon** [comment]
Ok, I hacked a solution in:
image

There's probably a better way to do this but it's 4am and thinking is hard.

**Pull request merged**
